### ISSUE TITLE
Category chooser text color and spacing

### ISSUE THREAD

**Issue by amotl** [Daemonite/discourse-material-theme#10]
## Problem I
When using the Light Theme, the text color of the category chooser element offers too less contrast for the currently selected item to be visible. This happens to the category chooser while creating or editing a topic.

![image](https://user-images.githubusercontent.com/453543/51080142-739d1e80-16d6-11e9-8540-f233ac2cd055.png)

## Problem II
After making the text visible, it occurs that the spacing between main and subcategory labels is non-existent.

![image](https://user-images.githubusercontent.com/453543/51080233-14400e00-16d8-11e9-8cb4-ba65ac31a298.png)

**Comment by amotl** [comment]
## Workaround
```css
/* Adjust category chooser */
.category-chooser {

    /* Add gap between category elements*/
    .selected-name {
        span + span {
            margin-left: 10px;
        }
    }

    /* Clear "color" attribute from badge label elements */
    .badge-wrapper {

        .badge-category {
            color: unset !important;
        }

    }
}
```

## Result
![image](https://user-images.githubusercontent.com/453543/51081288-6d19a180-16ec-11e9-9244-415a3448d3cb.png)
