### ISSUE TITLE
Rendered checkboxes in post content slightly off

### ISSUE THREAD

**Issue by amotl** [Daemonite/discourse-material-theme#15]
## Problem
The checkboxes rendered by the [Discourse checklist rendering plugin](https://github.com/discourse/discourse-checklist) by writing down `[]` or `[x]` in the markup are slightly off.

![image](https://user-images.githubusercontent.com/453543/51087159-99b2d500-174f-11e9-8b80-5c820021fc11.png)

## Workaround
```css
/* Fix DMT#15: Checkboxes slightly off */
.contents span.chcklst-box::before {
    display: inline-flex;
    margin-right: 0.1rem;
    margin-bottom: 0.1rem;
}
```
![image](https://user-images.githubusercontent.com/453543/51087175-b818d080-174f-11e9-85a3-ce0f15cab873.png)

Thank you in advance for your attention.
