### ISSUE TITLE
User card has odd margin attribute

### ISSUE THREAD

**Issue by amotl** [Daemonite/discourse-material-theme#16]
## Problem
The user card currently has a large spacing due to some margin setting which seems to be nailed to `80px`.

![image](https://user-images.githubusercontent.com/453543/51088143-9a9e3380-175c-11e9-91c1-18295f9e1ba4.png)

**Comment by amotl** [comment]
## Workaround
This patch
```css
/* Fix odd margin attribute with user card (DMT#16) */
#user-card .bio, #group-card .bio {
    margin-top: unset !important;
}
```
makes the issue go away:

![image](https://user-images.githubusercontent.com/453543/51088144-9f62e780-175c-11e9-976a-c1731681fe47.png)
