### ISSUE TITLE
Size limit on topic status icon

### ISSUE THREAD

**Issue by amotl** [Daemonite/discourse-material-theme#7]
Hi @sesemaya,

we just wanted to drop another minor issue we found while implementing your theme.

## Problem
The topic status icon is slightly off.

## Workaround
```css
/* Fix DMT#7: Remove size limit from topic status icon */
.topic-statuses i.d-icon {
    height: unset !important;
    width: unset !important;
}
```

## Before
![image](https://user-images.githubusercontent.com/453543/51079887-d1c70300-16d0-11e9-8c3f-42efd656e797.png)

## After
![image](https://user-images.githubusercontent.com/453543/51079897-00dd7480-16d1-11e9-9f99-762c1db5d24d.png)

----

Thank you in advance for having a look.

With kind regards,
Andreas.

**Comment by sesemaya** [comment]
I can't reproduce this problem here. Does this happen on a specific page with certain settings turned off/on?

**Comment by amotl** [comment]
Thanks. After checking this again, the displacement problem we saw before seems to have disappeared, both on vanilla and with our amendments.

However, we found it pleasant to add some spacing here.
```css
/* Divert DMT#7: Adjust spacing between topic status icon and topic title */
.topic-statuses i.d-icon {
    margin-right: 0.25em;
}
```

## Without margin
![image](https://user-images.githubusercontent.com/453543/51385926-f5e77180-1b20-11e9-8dba-2d97979c8687.png)
![image](https://user-images.githubusercontent.com/453543/51385966-19122100-1b21-11e9-9b18-71b3a9bcd4be.png)

## With margin
![image](https://user-images.githubusercontent.com/453543/51385936-ff70d980-1b20-11e9-818b-4a67e79095f8.png)
![image](https://user-images.githubusercontent.com/453543/51385973-1f080200-1b21-11e9-8121-661b450b6220.png)
