### ISSUE TITLE
Post 

### ISSUE THREAD

**Issue by amotl** [Daemonite/discourse-material-theme#9]
## Problem
When editing posts, the "Save Edit" / "Cancel" Buttons 
![image](https://user-images.githubusercontent.com/453543/51080032-5b2c0480-16d4-11e9-8161-8f57bd136ff9.png)

are missing under certain conditions like depicted in this screenshot
![image](https://user-images.githubusercontent.com/453543/51080025-35066480-16d4-11e9-8c5e-4fd2a48b4628.png)

## Observations
It looks like this **does not happen** with short posts on the first position i.e. where the distance from the top of the page is short. Saying that, it **does happen** with first posts which are vertically larger and also usually happens with subsequent posts on a page, as they usually **do** have a reasonable distance from the top.

**Comment by amotl** [comment]
## Workaround
We found that by resetting the `display` css attribute here, the buttons stopped being displaced.
```css
/* Fix DMT#9: "Save Edit" / "Cancel" buttons slightly off when editing posts */
#reply-control .submit-panel {
    display: initial !important;
}
```
